services:
  mongodb:
    container_name: mongodb
    image: mongodb/mongodb-community-server
    restart: always
    ports:
      - 27017:27017
    volumes:
      - "./sample_collection.bson:/data/sample_collection.bson"
#    command: ['mongorestore', '-d', 'db_name', '-c', 'collection_name', '/data/sample_collection.bson']
